export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SCHEDULE_ROUTE = '/schedule'
export const BASKET_ROUTE = '/basket'
export const LESSON_ROUTE = '/lesson'
